### ISSUE TITLE
GitHub encourages communication and ongoing review.

### ISSUE THREAD

**Issue by cherry98k** [hpcaitech/PaLM-colossalai#28]
Why not directly answering the issues #27?
Have you reproduced all model details? Yes or Not?
Have you really reproduced similar results (e.g., the sample model outputs in Appendix F)? Yes or Not?

As you said GitHub encourages communication and ongoing review, why are you tracking down my real identity and closing the issues, rather than directly answering the questions? Is that how your team treating users' questions?

If you didn't overclaim, please show the reproduced results, rather than closing or deleting the issues.

GitHub is a place to share source codes and encourage open collaboration, but it does not encourage to make fake news.
Chasing the clout is your freedom, but you also have to be respectful to the spirit of open source.
A high school student even knows better than you about how to respect others.

**Comment by feifeibear** [comment]
Cherry, 
As one of the developers, I would like to express my sympathy if this project makes you feel uncomfortable.
As stated, we reproduced the model architecture and applied a set of parallel strategies to it. As we know, PaLM is a large language model product and the implementation of the model architect is just the first step. We believe our efforts make some beneficial contributions to the community.
We are looking forwards to your technical feedback on the project!

**Comment by cherry98k** [comment]
Feieibear, Thanks for your prompt response and I also notice that the latest PR #29 has adjusted the overclaiming statements. I really appreciate your contributions to the community.
Btw, it is a pity for anyone who works with the guy @fastalgo, who has bad diathesis and no respect to others. 
Unlike him, you are an excellent and leadership developer.
