### ISSUE TITLE
Gemini badcase

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/PaLM-colossalai#40]
See MR #41 
The launching script
```
env OMP_NUM_THREADS=12 torchrun --standalone --nproc_per_node=4 train.py --from_torch --config=./configs/palm_8b_zero_gemini_badcase.py
```

When using 'auto', the error log. failed in the 1st iteration's backward

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/5706969/164134180-ae9b0c84-b14d-4219-bd97-ca444f3e4260.png">

However, using 'cpu' will pass.
That indicates our gemini is not robust enough.

**Comment by feifeibear** [comment]
I suggest the program failed on hybrid adam. ColossalAl wrongly estimated the margin space for OS when using Gemini.
@ver217

**Comment by feifeibear** [comment]
At the 1st ADAM computation, we found 3.411 GB margin memory space on CUDA.
Therefore we move 3.411 GB of data from CPU to CUDA.

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/5706969/164177786-f55f9926-6f9e-4011-8316-5ffdefa2d885.png">

**Comment by ver217** [comment]
Adding `PYTORCH_NO_CUDA_MEMORY_CACHING=1` can also work.

**Comment by ver217** [comment]
I think fragmentation leads to this issue, rather than gemini itself.
