### ISSUE TITLE
Warning When Using Different HuggingFace Datasets

### ISSUE THREAD

**Issue by conceptofmind** [hpcaitech/PaLM-colossalai#45]
Hello,

Any idea if this warning will impact the training of the model when using alternative datasets? Or can it be ignored? I understand that PaLM needs concatenated input sequences of length 2048.

Warning thrown:

**Token indices sequence length is longer than the specified maximum sequence length for this model (1366 > 1024). Running this sequence through the model will result in indexing errors.**

Contained Example:

```
dataset = load_dataset("the_pile", 'enron_emails')

print(dataset)

tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

seq_len = 2048

def tokenize(examples):
    seq_length = seq_len
    examples = tokenizer(examples["text"])
    concatenated_examples = {k: list(chain(*examples[k])) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    if total_length >= seq_length:
        total_length = (total_length // seq_length) * seq_length

    result = {
        k: [t[i : i + seq_len] for i in range(0, total_length, seq_length)]
        for k, t in concatenated_examples.items()
    }

    result["labels"] = copy.deepcopy(result["input_ids"])

    return result

tokenized_dataset = dataset.map(
    tokenize, batched=True, num_proc=16, keep_in_memory=True, remove_columns= ['text', 'meta']
)
```

Thank you,

Enrico

**Comment by feifeibear** [comment]
In my humble option, the reason is that the max seq len of the embedding of your pretrained model is limited to 1024. Maybe you need to modified the embedding logic. It is common in Bert pertaining using longer sequences. Because max len of bert embedding is only 512. The GPT2 may fall into the same cases.

**Comment by conceptofmind** [comment]
Hi @feifeibear ,

Thank you for the response.

Is the GPT2Tokenizer in the `build_data_from_wikitext()` function pre-trained on the wiki dataset with a specific sequence length of 2048 tokens first? I noticed you set the sequence length to 512 when constructing the dataset: `seq_len: int = 512`. The warning I provided is being thrown before I input any tokenized data into your PaLM model.

``` 
# Vocab in the paper is sentencepiece. GPT2Tokenizer uses tokenizers like sentencepiece.
tokenizer = GPT2Tokenizer(vocab_file=tokenizer_path + "/vocab.json", merges_file=tokenizer_path + "/merges.txt")
```

Thank you again,

Enrico
